=== AltranArmada/STROMBOLI/Cfg_IP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="BDD_Cfg_Reseau" type="BDD_Cfg_ReseauType">
    <xs:annotation>
      <xs:documentation>- Proposition descriptif reseau STROMBOLI pour Mesures Syst√®me - objectif du fichier : decrire les caracteristiques des trames IP</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:simpleType name="IPv4AddressType">
    <xs:annotation>
      <xs:documentation>IPv4 address in dot-decimal notation. Equivalent to [0-255].[0-255].[0-255].[0-255]</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])" />
    </xs:restriction>
  </xs:simpleType>  
  <xs:complexType name="PLAGEType">
    <xs:sequence>
      <xs:element type="IPv4AddressType" name="IP_BASE"/>
      <xs:element type="IPv4AddressType" name="IP_MIN"/>
      <xs:element type="IPv4AddressType" name="IP_MAX"/>
      <xs:element type="IPv4AddressType" name="IP_MASQUE"/>
      <xs:element type="IPv4AddressType" name="IP_BROADCAST"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="IDENTIFIANT" use="optional"/>
  </xs:complexType>
  <xs:complexType name="EQUIPType">
    <xs:sequence>
      <xs:element type="xs:string" name="NOM"/>
      <xs:element type="IPv4AddressType" name="IP"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="IDENTIFIANT" use="optional"/>
  </xs:complexType>
  <xs:complexType name="BDD_Cfg_ReseauType">
    <xs:sequence>
      <xs:element type="PLAGEType" name="PLAGE" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="EQUIPType" name="EQUIP" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AltranArmada/STROMBOLI/stromboli_lib/xml/20190701_Exemple_Cfg_IP__gen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<BDD_Cfg_Reseau xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/mcorset/Documents/Altran/Safran/STROMBOLI/stromboli_lib/xsd/Cfg_IP.xsd">
  <PLAGE IDENTIFIANT="SYS_CMD">
    <IP_BASE>192.168.100.0</IP_BASE>
    <IP_MIN>192.168.100.1</IP_MIN>
    <IP_MAX>192.168.101.254</IP_MAX>
    <IP_MASQUE>255.255.254.0</IP_MASQUE>
    <IP_BROADCAST>192.168.101.255</IP_BROADCAST>
  </PLAGE>
  <PLAGE IDENTIFIANT="SYS_SURV">
    <IP_BASE>192.168.100.0</IP_BASE>
    <IP_MIN>192.168.100.1</IP_MIN>
    <IP_MAX>192.168.101.254</IP_MAX>
    <IP_MASQUE>255.255.254.0</IP_MASQUE>
    <IP_BROADCAST>192.168.101.255</IP_BROADCAST>
  </PLAGE>
  <EQUIP IDENTIFIANT="PCPBISUOP1_CPU_P">
    <NOM>PCP BIS Voie 1 Principale</NOM>
    <IP>192.168.100.11</IP>
  </EQUIP>
  <EQUIP IDENTIFIANT="PCPBISUOP1_CPU_A">
    <NOM>PCP BIS Voie 1 Secondaire</NOM>
    <IP>192.168.100.12</IP>
  </EQUIP>
</BDD_Cfg_Reseau>
